export const orderActionTypes = {
    LOAD_ORDERS_BY_EMAIL_REQUEST: 'LOAD_ORDERS_BY_EMAIL_REQUEST',
    LOAD_ORDERS_BY_EMAIL_SUCCESS: 'LOAD_ORDERS_BY_EMAIL_SUCCESS',
    LOAD_ORDERS_BY_EMAIL_FAILURE: 'LOAD_ORDERS_BY_EMAIL_FAILURE',
    PLACE_ORDER_REQUEST: 'PLACE_ORDER_REQUEST',
    PLACE_ORDER_SUCCESS: 'PLACE_ORDER_SUCCESS',
    PLACE_ORDER_FAILURE: 'PLACE_ORDER_FAILURE',
    CLEAR_ORDERS: 'CLEAR_ORDERS'
}
