export const orderActionTypes = {
    LOAD_ORDERS_BY_EMAIL_REQUEST: 'LOAD_ORDERS_BY_EMAIL_REQUEST',
    LOAD_ORDERS_BY_EMAIL_SUCCESS: 'LOAD_ORDERS_BY_EMAIL_SUCCESS',
    LOAD_ORDERS_BY_EMAIL_FAILURE: 'LOAD_ORDERS_BY_EMAIL_FAILURE'
}
