export const categoryActionTypes = {
    LOAD_CATEGORIES_REQUEST: 'LOAD_CATEGORIES_REQUEST',
    LOAD_CATEGORIES_SUCCESS: 'LOAD_CATEGORIES_SUCCESS',
    LOAD_CATEGORIES_FAILURE: 'LOAD_CATEGORIES_FAILURE',
}
