export const userActionTypes = {
    REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_FAILED: 'USER_REGISTER_FAILED',
    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILED: 'USER_LOGIN_FAILED',
    LOGOUT: 'USER_LOGOUT',
}
